project:
  type: website
  output-dir: docs

website:
  title: "LVA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pages/about.qmd
      - pages/projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



